### ISSUE TITLE
Support main and master branches

### ISSUE THREAD

**Issue by pchr-srf** [gitcd-io/gitcd#110]
Some repositories are switching from `master` to `main` - would be nice if git-cd would support both:

![image](https://user-images.githubusercontent.com/21658108/134160651-523b6d32-21cc-4032-a218-8d220e7a7677.png)

**Comment by claudio-walser** [comment]
Ah, few months ago. I do need notifications 🙈
I actually changed the default in march 2021 already https://github.com/gitcd-io/gitcd/commit/14ba86c5e671e66c94715701956db3623701e38f
For your repos which you already have setup, you need to do a git-cd init or change the .gitcd file directly in your repository.

**Comment by pchr-srf** [comment]
Works for nora! Many thanks!
