### ISSUE TITLE
Resume test/refresh after merge

### ISSUE THREAD

**Issue by LePhil** [gitcd-io/gitcd#98]
When a merge error is encountered during `git-cd test` or `git-cd refresh`, one has to manually finish the task (fix conflict, `git commit`, `git push`, `git checkout -`).
Would be awesome if one could either call `git-cd test`/`git-cd refresh` to resume the task after merging or `git-cd resume`.
Deluxe version would continue automatically after merge commit of course ;)

**Comment by claudio-walser** [comment]
Tough one, pretty sure i'll find some solution. 
And thanks for the input, sounds like a very valuable feature for me.
